// No change or addition from testa.h

#include "zzincl.h" // generated by zzprep
class Library{
    ZZ_EXT_Library
public:
    Library(){}
};
class Author {
    ZZ_EXT_Author
public:
    Author(){}
    Author(char *name);
};
class Book {
    ZZ_EXT_Book
    int num;
public:
    Book(){num=0;}
    Book(int i){num=i;}
    int getNum(){return num;}
};

ZZ_HYPER_NAME(aName,Author); // multiple authors reported as one 'name'
ZZ_HYPER_SINGLE_COLLECT(authors,Library,Author);
ZZ_HYPER_DOUBLE_AGGREGATE(books,Author,Book); 
ZZ_HYPER_UTILITIES(util); // allocation and disk saving utilities
