// No change in this file

#include <string.h>
#include "zzincl.h"
#include "testa.h"

Author::Author(char *name){
    char *p; int sz;
    sz=strlen(name);
    p=new char[sz+1];
    strcpy(p,name);
    aName.add(this,p);
}

#include "zzfunc.c" // generated by zzprep, can be compiled separately
