// Changes: functions util.mode() and util.blkAlloc() are used and must
//          be identical with those that generated the data (testc1.cpp)
// Also note that memory blasting does not return the root type.
// A check for util.error() is fully sufficient for all three saving modes.

#define ZZmain // must be defined in exactly on file of the program
#include "zzincl.h" // generated by zzprep
#include "testa.h"

int main(){
    int i; Library *lib; Author *aut; Book *bk;
    void* v[1]; char* t[1]; // for saving to disk
    authors_iterator aIt;
    books_iterator bIt;

    util.mode(0,0,0,0);  // same as in testc1.cpp
    util.blkAlloc(0,10); // same as in testc1.cpp

    // get the data from file "myFile"
    util.open("myFile",1,v,t); // 1 root, results in v,t
    if(util.error()){
        printf("error in restoring file 'myFile'\n");
        return 1;
    }
    lib=(Library*)v[0]; // the only place in DOL where you have to cast

    // print the saved data
    aIt.start(lib);
    ITERATE(aIt,aut){    // go through all authors in 'lib'
        bIt.start(aut);
        ITERATE(bIt,bk){ // go through all book of author 'aut'
            printf("author=%s book=%d\n",aName.fwd(aut), bk->getNum());
        }
    }
    return 0;
}
